In [7]:
import torch
import pandas as pd

In [11]:
A = torch.ones(16).reshape(4,4)
A

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
B = A.T
B == B.T

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [18]:
A = torch.arange(20).reshape(5,4)
B = torch.arange(20)+torch.arange(20)
B = B.reshape(5,4)
A.T + B.T == (A+B).T

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [25]:
import torch
A = torch.randint(0,100,(4,4))
B = A + A.T
B == B.T

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [33]:
A = torch.randint(0,100,(2,3,4))
A

tensor([[[23,  3, 87, 18],
         [79, 89,  6, 21],
         [65, 32, 79, 96]],

        [[53, 11, 28, 23],
         [67, 26, 56, 92],
         [61, 22, 86, 89]]])

In [34]:
A = torch.randint(0,100,(3,4))
A/A.sum(axis=1,keepdim=True)

tensor([[0.2056, 0.0327, 0.4252, 0.3364],
        [0.1505, 0.4369, 0.1214, 0.2913],
        [0.2107, 0.2645, 0.3884, 0.1364]])

In [39]:
import torch

X = torch.tensor(
        [  # 第0组
            [  # 第1组
                [23,  3, 87, 18],
                [79, 89,  6, 21],
                [65, 32, 79, 96]
            ],
            [
                [53, 11, 28, 23],
                [67, 26, 56, 92],
                [61, 22, 86, 89]
            ]
        ]
)
X = X.float()
torch.norm(X)
A = torch.tensor(
    [
        [  # 第0组
            [  # 第1组
                [23,  3, 87, 18],
                [79, 89,  6, 21],
                [65, 32, 79, 96]
            ],
            [
                [53, 11, 28, 23],
                [67, 26, 56, 92],
                [61, 22, 86, 89]
            ]
        ],

        [  # 第0组的第二个
            [
                [12, 34, 56, 78],
                [90, 11, 22, 33],
                [44, 55, 66, 77]
            ],
            [
                [88, 99, 10, 20],
                [30, 40, 50, 60],
                [70, 80, 90, 100]
            ]
        ]
    ]
)

A = A.float()
torch.norm(A),torch.norm(X)

(tensor(419.4174), tensor(290.3549))