In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

true_w = torch.tensor([2,-3.4])
true_b = 4.2

features, labels = d2l.synthetic_data(true_w,true_b,1000)
features,labels

(tensor([[-1.1848,  0.0608],
         [-1.4262,  0.3892],
         [-1.5882,  1.1379],
         ...,
         [ 0.2493,  0.2227],
         [-0.0675, -0.9939],
         [-0.8481,  0.1944]]),
 tensor([[ 1.6064e+00],
         [ 2.2076e-02],
         [-2.8540e+00],
         [ 2.7337e+00],
         [ 9.4444e+00],
         [ 2.6689e+00],
         [ 2.0338e+00],
         [ 8.4477e+00],
         [ 6.5069e+00],
         [ 6.8093e+00],
         [-5.4088e+00],
         [ 1.0141e+01],
         [ 6.1721e+00],
         [-1.3735e+00],
         [ 3.1146e+00],
         [ 8.0489e+00],
         [ 7.4397e+00],
         [ 1.5428e-01],
         [ 3.5170e+00],
         [ 3.4499e+00],
         [ 4.1487e+00],
         [ 1.7640e+00],
         [ 3.7124e+00],
         [ 7.1455e+00],
         [ 1.6760e+00],
         [ 8.8929e-01],
         [ 6.8240e+00],
         [ 3.8916e+00],
         [ 1.0736e+01],
         [ 4.0104e+00],
         [ 6.5143e+00],
         [ 1.6057e-02],
         [ 4.5269e+00],
         [ 2.9866e

In [3]:
def load_array(data_arrays,batch_size,is_train=True):
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

batch_size = 10
data_iter = load_array((features,labels),batch_size)

next(iter(data_iter))

[tensor([[ 0.8636,  0.1695],
         [ 0.3952, -1.9810],
         [ 0.7117, -1.8353],
         [ 0.1077, -1.2614],
         [-0.3597, -0.2596],
         [-1.4897, -0.6567],
         [ 2.1369,  1.0480],
         [-1.0408,  0.2806],
         [-0.3940, -1.2911],
         [ 0.4760, -0.8457]]),
 tensor([[ 5.3540],
         [11.7297],
         [11.8656],
         [ 8.7045],
         [ 4.3645],
         [ 3.4499],
         [ 4.9168],
         [ 1.1533],
         [ 7.8098],
         [ 8.0062]])]

In [4]:
from torch import nn
net = nn.Sequential(nn.Linear(2,1))


In [6]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [7]:
loss = nn.MSELoss()

In [8]:
trainer = torch.optim.SGD(net.parameters(),lr=0.03)

In [9]:
num_epochs = 3
for epoch in range(num_epochs):
    for X,y in data_iter:
        l = loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features),labels)
    print(f'epoch{epoch+1},loss{l:f}')

epoch1,loss0.000168
epoch2,loss0.000100
epoch3,loss0.000099


In [10]:
w = net[0].weight.data
print('w的估计误差', true_w-w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：',true_b-b)

w的估计误差 tensor([-0.0003, -0.0004])
b的估计误差： tensor([-0.0011])
